<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.51IVYBf' shared service.

return $this->privates['.service_locator.51IVYBf'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('message' => function (): \App\Entity\Messages {
    return ($this->privates['.errored..service_locator.51IVYBf.App\Entity\Messages'] ?? $this->load('getMessagesService.php'));
}));
