<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.9AMeiiU' shared service.

return $this->privates['.service_locator.9AMeiiU'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('categoriesRepository' => function (): \App\Repository\CategoriesRepository {
    return ($this->privates['App\Repository\CategoriesRepository'] ?? $this->load('getCategoriesRepositoryService.php'));
}, 'shopcartRepository' => function (): \App\Repository\ShopcartRepository {
    return ($this->privates['App\Repository\ShopcartRepository'] ?? $this->load('getShopcartRepositoryService.php'));
}, 'user' => function (): \App\Entity\User {
    return ($this->privates['.errored..service_locator.9AMeiiU.App\Entity\User'] ?? $this->load('getUserService.php'));
}));
