<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zBPsdEs' shared service.

return $this->privates['.service_locator.zBPsdEs'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('categoriesRepository' => function (): \App\Repository\CategoriesRepository {
    return ($this->privates['App\Repository\CategoriesRepository'] ?? $this->load('getCategoriesRepositoryService.php'));
}, 'user' => function (): \App\Entity\User {
    return ($this->privates['.errored..service_locator.zBPsdEs.App\Entity\User'] ?? $this->load('getUser3Service.php'));
}));
