<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.p2SiWGF' shared service.

return $this->privates['.service_locator.p2SiWGF'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('category' => function (): \App\Entity\Categories {
    return ($this->privates['.errored..service_locator.p2SiWGF.App\Entity\Categories'] ?? $this->load('getCategories2Service.php'));
}));
