<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.K3L83Kj' shared service.

return $this->privates['.service_locator.K3L83Kj'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('messagesRepository' => function (): \App\Repository\MessagesRepository {
    return ($this->privates['App\Repository\MessagesRepository'] ?? $this->load('getMessagesRepositoryService.php'));
}));
