<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.9okS_qG' shared service.

return $this->privates['.service_locator.9okS_qG'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('shopcart' => function (): \App\Entity\Shopcart {
    return ($this->privates['.errored..service_locator.9okS_qG.App\Entity\Shopcart'] ?? $this->load('getShopcartService.php'));
}));
