<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.RELFidE' shared service.

return $this->privates['.service_locator.RELFidE'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('order' => function (): \App\Entity\Orders {
    return ($this->privates['.errored..service_locator.RELFidE.App\Entity\Orders'] ?? $this->load('getOrdersService.php'));
}));
