<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.QJs22mL' shared service.

return $this->privates['.service_locator.QJs22mL'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('categoriesRepository' => function (): \App\Repository\CategoriesRepository {
    return ($this->privates['App\Repository\CategoriesRepository'] ?? $this->load('getCategoriesRepositoryService.php'));
}, 'product' => function (): \App\Entity\Product {
    return ($this->privates['.errored..service_locator.QJs22mL.App\Entity\Product'] ?? $this->load('getProduct3Service.php'));
}, 'resimlerRepository' => function (): \App\Repository\ResimlerRepository {
    return ($this->privates['App\Repository\ResimlerRepository'] ?? $this->load('getResimlerRepositoryService.php'));
}));
