<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.WRDb4EJ' shared service.

return $this->privates['.service_locator.WRDb4EJ'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('detailRepository' => function (): \App\Repository\OrderDetailRepository {
    return ($this->privates['App\Repository\OrderDetailRepository'] ?? $this->load('getOrderDetailRepositoryService.php'));
}, 'orders' => function (): \App\Entity\Orders {
    return ($this->privates['.errored..service_locator.WRDb4EJ.App\Entity\Orders'] ?? $this->load('getOrders2Service.php'));
}));
