<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pTQmj42' shared service.

return $this->privates['.service_locator.pTQmj42'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('orderDetail' => function (): \App\Entity\OrderDetail {
    return ($this->privates['.errored..service_locator.pTQmj42.App\Entity\OrderDetail'] ?? $this->load('getOrderDetailService.php'));
}));
