<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Y21gY5W' shared service.

return $this->privates['.service_locator.Y21gY5W'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('categoriesRepository' => function (): \App\Repository\CategoriesRepository {
    return ($this->privates['App\Repository\CategoriesRepository'] ?? $this->load('getCategoriesRepositoryService.php'));
}, 'ordersRepository' => function (): \App\Repository\OrdersRepository {
    return ($this->privates['App\Repository\OrdersRepository'] ?? $this->load('getOrdersRepositoryService.php'));
}, 'shopcartRepository' => function (): \App\Repository\ShopcartRepository {
    return ($this->privates['App\Repository\ShopcartRepository'] ?? $this->load('getShopcartRepositoryService.php'));
}));
