<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1aOc3L9' shared service.

return $this->privates['.service_locator.1aOc3L9'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('product' => function (): \App\Entity\Product {
    return ($this->privates['.errored..service_locator.1aOc3L9.App\Entity\Product'] ?? $this->load('getProductService.php'));
}, 'resimlerRepository' => function (): \App\Repository\ResimlerRepository {
    return ($this->privates['App\Repository\ResimlerRepository'] ?? $this->load('getResimlerRepositoryService.php'));
}));
