<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.51IVYBf.App\Entity\Messages' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.51IVYBf": it references class "App\\Entity\\Messages" but no such service exists.');
