<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.9okS_qG.App\Entity\Shopcart' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.9okS_qG": it references class "App\\Entity\\Shopcart" but no such service exists.');
