<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFWERucx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFWERucx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFWERucx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFWERucx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFWERucx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'FWERucx',
    'container.build_id' => '08a07bd6',
    'container.build_time' => 1548001566,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFWERucx');
